export const GET_POSTS_QUERY = 'SELECT * FROM todos ORDER BY id ASC'
export const SET_POST_QUERY = 'INSERT INTO todos (value, "isFinished") values($1, $2) RETURNING *'
export const EDIT_POST_QUERY = 'UPDATE todos SET value = $1, "isFinished" = $2 WHERE id = $3'
export const DELETE_POST_QUERY = 'DELETE FROM todos WHERE id = $1'
export const SELECT_ALL_QUERY = 'UPDATE todos SET "isFinished" = $1'
export const DELETE_SELECTED = 'DELETE FROM todos WHERE "isFinished" = true'